### ISSUE TITLE
where is the manual? having problems using font-manager. collections unrealible 

### ISSUE THREAD

**Issue by reddot15** [FontManager/master#10]
lets say i already have 1000 fonts, i put them in a collection. then i add 1000 more fonts, then i want to put the new fresh collection but other fonts i have will be added to the collection since i have no idea how to add fresh imported fonts to new collection (without deselecting 1000 fonts individualy). im bad at explaining, but where are settings? 

it would be easy lets say to add 1000 fonts, add them to a collection, then turn off there visibility so they wont show up in category. disabling is not enough.

that would allow me to add another 100, move them to a category, then turn there visibility and add more. fresh ones to a new collection. if the fonts are visible then i must deselect each one individually to add the new ones to a new collection.

is it possible to do this im using version 0.7.2 in linux mint 17.2 mate

**Comment by JerryCasiano** [comment]
The manual hasn't been written yet. You're more than welcome  to help on that front. If you open the help dialog it will tell you that.

As far as your issue with sorting fonts, you realize there is an Unsorted category, right? So if you add fonts to a collection they shouldn't show up in that category.

But maybe I misunderstood.

**Comment by JerryCasiano** [comment]
Also please explain what you mean by unreliable?

**Comment by reddot15** [comment]
thanks jerry, btw your first reply fixed my problem. i will be using this frequent. i would love to make a manual once i figure all the pieces. the other thing i noticed is how do i refresh the font cache after i add a source? im currently restarting the app do refresh.

as for unreliable collections, not really unreliable. but adding new fonts wont go straight to a certain collection by selecting it? or i dont know how to add new fonts when importing them. so i have to manually select them and add them to the collection, just an extra step. 

no need for font visibility since unsorted fonts is awesome. works perfectly.

**Comment by reddot15** [comment]
you can close this one. solved!!! thanks for your help

**Comment by JerryCasiano** [comment]
You shouldn't need to refresh anything,  the application should refresh itself.

If you're using a mainstream desktop environment,  Gnome, Xfce, etc the desktop will pick up fonts within a few seconds.

BTW,  sources aren't enabled by default, you'll need to flip the switch if you want them available to other applications.

As far as adding new fonts directly to a collection, it's on my to-do list. I know a lot has changed from the previous version, jarring really. But it's still in the middle of a full rewrite, so not everything is sorted out yet. Still a ton of work to be done. I released it because it's mostly usable and the last version was pretty broken/outdated.

Anyway, glad that suggestion works for you.

**Comment by JerryCasiano** [comment]
Simply select the fonts you want to add to the collection and drag them
over, the view will switch from category to collections when you are
dragging and back when you're done. ;-)

Also you can select and drag multiple fonts.

You can also install fonts (folders, files, archives) by dragging them onto
the font list.

Hope that helps, if you have any other questions, feel free to ask.
