### ISSUE TITLE
Lubuntu 16.04

### ISSUE THREAD

**Issue by davekimble2** [FontManager/master#18]
Installed font-manager from Ubuntu repo (no version displayable)
Ran font-manager as root -  it couldn't remove any fonts - list of selectable fonts was blank
Uninstalled.

Added repo ppa:font-manager/staging
Installed font-manager 0.7.3
Ran font-manager as root - migrated settings automatically OK
Still couldn't remove any fonts
![screenshot from 2016-08-05 12-33-38](https://cloud.githubusercontent.com/assets/6146050/17424613/1d8ce01a-5b09-11e6-8958-dec2e4bb7feb.png)

**Comment by JerryCasiano** [comment]
Running as root is not supported.

**Comment by JerryCasiano** [comment]
As an aside. I'm not sure what your expectations are but Font Manager is not intended to allow removal of system files. It will allow removal of any fonts owned by you and stored in the default location. So if you install fonts using Font Manager they will show up in that dialog.

**Comment by davekimble2** [comment]
OK, but that's a bit odd - this is supposed to be a front end for all the things you can do from the command line, isn't it?  

My expectation was that:
running as **user** you could remove your own fonts or disable system fonts for that user, 
running as **root** you could remove system fonts

Instead of an empty list, you might output a message "No fonts can be removed", so it doesn't look broken.

Attempts to remove system fonts could use the usual authentication dialog to get root privileges, and have a warning "This will remove the fonts from all users.  Proceed?  OK/Cancel"

**Comment by JerryCasiano** [comment]
Your expectation is wrong as I explained previously. 
This is a user level application, it allows users to disable fonts they don't want without affecting any other account which has the same effect as actual removal as far as the user is concerned.
Font Manager will never allow direct removal of system files it doesn't track, of course anyone can modify the source to do this but it won't be me.

System wide font management using PolicyKit/PackageKit is a fine idea but a very, very low priority for me, not even worth talking about at this point.  Sorry.

As far as better feedback rather than an empty list, will fix in next release.

Please see https://raw.githubusercontent.com/FontManager/master/master/README
