### ISSUE TITLE
Custom preview text

### ISSUE THREAD

**Issue by nyov** [FontManager/master#28]
I wish this would support custom preview texts.

It would also be very useful to be able to click on a font name in the "Browse" mode and get to the font properties.

Lastly, the font properties should list the filename and location of the font. It's painful to have to search the various font directories for the actual font, or use another font manager to get that info.
Oh, and some important information is missing, such as font type (Truetype, Type1, OpenType, ...)

**Comment by JerryCasiano** [comment]
> I wish this would support custom preview texts

It already does, in the preview pane you can set justification, edit the text and reset it to default.

Supporting custom text in other areas is the plan, saving sample sentences, etc is planned. But it's not a high priority. 

> It would also be very useful to be able to click on a font name in the "Browse" mode and get to the font properties.

Browse mode is probably going away since the same can be achieved by simply expanding the regular font list and collapsing the lower pane. If it does stick around it will simply be that not a separate view rendered differently the way it is now.

> Lastly, the font properties should list the filename and location of the font. 

I don't know about that, it's already crowded in my opinion. I'm more inclined to provide a "Show in folder" type of thing or maybe allow setting which fields are displayed in UI preferences.

Is this something that you find yourself needing all the time? Would a button that opened a file manager suffice or would it be more annoying than useful?

BTW, if you run the application from the command line it will spit out a bunch of mostly useless information but among all that noise you'll see the path to the selected font. So, a little workaround for now. 

> Oh, and some important information is missing, such as font type (Truetype, Type1, OpenType, ...)

Hmm. I thought I put this back...
Definitely an important bit that should be there.

Sorry, but I don't have any timeframe for these changes, for sure they will happen though. It's just that I have very little free time these days and have mostly been reworking the lower layer lately, I'm not really happy with it. Still a long way to 1.0 still prototyping. ;-)

Thanks your interest and feedback!

**Comment by nyov** [comment]
Thank you for the reply!

I've found the custom text editing icon. However that requires clicking through each font to see a preview. Very annoying in my opinion, if I want to preview a text/symbol in a hundred fonts.
It would be much nicer in the Browse mode.

If the browse mode goes away, the only preview is the actual font list, and that doesn't allow changing the font size (currently). But if they both got merged, that would be okay.
The "Waterfall" view is also only available after selecting a specific font, so that one doesn't count ;)

I would really prefer to see the actual font file name(s) and info in a way such as Fontmatrix does (copy-pasteable text). A folder open/filemanager button wouldn't help me with some hundreds of font files in a directory, some of which are just numbered.
And finding the exact font file name is pretty important to me, as I often need to reference them in LaTeX or other scripts.
BTW, I do run font-manager from the terminal and I don't see font filenames there. Perhaps that's only in some debug mode compilation? I only see a lot of Pango warnings. (v0.7.3, debian package)

Fontmatrix info example:
```
File
/­usr/­share/­fonts/­truetype/­ebgaramond/­EBGaramond08-Regular.ttf
Glyphs count
2213
Font Type
TrueType
Charmaps List
Unicode, Apple Roman
Not Restricted
This font may be embedded and permanently installed on the remote system by an application. The user of the remote system acquires the identical rights, obligations and licenses for that font as the original purchaser of the font, and is subject to the same end-user license agreement, copyright, design patent, and/or trademark as was the original purchaser.
Panose
Unicode Ranges
- Basic Latin
- Latin-1 Supplement
- Latin Extended-A
- Spacing Modifier Letters
- Greek and Coptic
- General Punctuation
- Currency Symbols
- Letterlike Symbols
- Mathematical Operators
- Private Use Area
- Alphabetic Presentation Forms
```
If font-manager could skip empty code ranges and only count the actual mapped glyphs in the Characters view, that might also be nice.

And I'm not asking for these features _right now_, and since debian release freeze is upcoming and the next debian release is probably in some two years I can't really expect to see anything before then anyway :)

**Comment by JerryCasiano** [comment]
Well, now that I understand what you want from browse mode, I think that makes sense.

Sorry, you have to pass -V on the command line.

The character map needs a rework, definitely agree. Currently using the gucharmap library for it but the intent is to do exactly what you're talking about. Only deal with characters the fonts actually contain and have categories/languages that make sense instead of the current everything.

**Comment by detly** [comment]
Am I missing something? I can't see the preview/properties/etc options anywhere. I'm using 0.7.3 from the Ubuntu 17.04 archives (not the PPA, apparently it's missing a release file).

Here's a screenshot. I'm not using the default theme, but changing back to Adwaita doesn't change it.

![font config](https://cloud.githubusercontent.com/assets/311239/26183449/13f67472-3bc2-11e7-8b1b-ee0054241c61.png)

**Comment by detly** [comment]
Oh duh. I was in "compare" mode, not "manage". It'd be nice to have custom text in compare mode too though.

**Comment by JerryCasiano** [comment]
Lol.

Yeah, it's on the to-do list for sure, custom text everywhere.

Unfortunately life gets in the way sometimes.

**Comment by detly** [comment]
It's not unfortunate 😉 If I have time, I'll look into it; if not, preview mode works great.

**Comment by poppe12** [comment]
Sorry for waking up an old thread but I can not find any option to change the displayed text "The quick brown..." Has the functionality been removed? I have tried the preview but I can not find any way to edit the text.  I'm  Swedish and use glyphs that does not get represented by that sentence. For me it is very hard to se how a font would treat Swedish that way. Also when programming I have noticed that some fonts change " to crooked " marks hence not working in a program. This would be good to see in an example text when reviewing fonts also.

Thanks for a good program any way.
/Johannes

**Comment by JerryCasiano** [comment]
No functionality has been removed, unfortunately none has been added either.

A lot of changes have taken place and some things are still broken in the testing branch but nothing on this front.

While in "Manage" mode and with the Preview option selected you *should* see formatting and editing icons in the upper part of that area. One is an insert text button and the other reverts any changes. The buttons on the other end allow you to set justification.

Probably not the best, or worst, UX decision I've ever made... but it is what it is, for now. 

Let me know if that's what you were after and if it worked for you.

![shitty_ux](https://user-images.githubusercontent.com/11490124/45905766-86a28080-bdbf-11e8-8b5d-1b1a2b7561a0.png)
.

**Comment by JerryCasiano** [comment]
Closing this out.

master allows editing of preview text in compare and browse mode.

I consider the custom text portion of this resolved for now.

Feel free to open separate issues for ideas posted here which are not implemented in master yet.

Thanks.
