### ISSUE TITLE
Not using headerbar

### ISSUE THREAD

**Issue by quassy** [FontManager/master#4]
I have installed FontManager on elementary OS 0.3 (based on Ubuntu 14.04, but using GTK 3.14) from your PPA (staging) and the app still uses a seperate titlebar. Judging from the screenshots on your website it should actually use a headerbar.

**Comment by JerryCasiano** [comment]
Sorry, but I don't test on Elementary and probably never will, wouldn't want to cheat them, you know?  ;-)

Anyway, you can always edit the check for headerbar support out, for now you'll find it in src/UX/Utils/Utils.vala look for a function named Gnome3 edit it so that it always returns true and compile.

Now that Xfwm supports headerbars that check is likely to go away soon. Will have to check if Unity supports them yet.

Hope that helps.

**Comment by JerryCasiano** [comment]
Opening this back up as a reminder. 

Swap out that check for one that enables CSD anytime compositing is enabled.

As I said, I don't use Elementary, so... Testers welcome.

**Comment by JerryCasiano** [comment]
Done. This should be fixed in the latest commit.

**Comment by JerryCasiano** [comment]
Feel free to open if it's not fixed.

And again apologies for the dismissive tone of my first reply. Elementary devs do rub me the wrong way. But that doesn't mean they don't have a nice product or that their users should have a shitty experience if it can be helped. Unfortunately their distribution is usually outdated by the time it hits, and they don't make their current easy to target for devs or users, at least that's my impression.

**Comment by quassy** [comment]
No worries! I will test on elementary and Ubuntu/Unity (which really is a nightmare...).

> wouldn't want to cheat them, you know? ;-)
There should be something like "Don't mention the war." for elementary ;)

**Comment by phisch** [comment]
@JerryCasiano I just noticed that the titlebar was missing (in favor of a box) and found this issue. One of my systems runs without compositor (intentionally), and was wondering why for this app a compositor is a requirement for CSD, since they work perfectly fine without.

**Comment by JerryCasiano** [comment]
@phisch 

Simply because support for GtkHeaderBar was quite the mess for quite a while, environments which were running a compositor were much more likely to have proper support.

That check should probably have gone away a while ago.

But honestly, the GTK 3 version is unlikely to see much in the way of changes / releases at this point, maybe one more release, maybe, if failures to build or some other serious issue pops up but aside from that probably not.

The focus is squarely on porting to GTK 4 at this time and GTK 4 pretty much requires a compositor.

**Comment by phisch** [comment]
GTK4 still does not rely on a compositor, here is how the widget factory looks without one:
![image](https://user-images.githubusercontent.com/1282767/162380554-77bb5e5c-28c5-4c9d-86b1-98700a2d3327.png)

GTK4 uses an rgba visual if possible, and if it can use one, and the window manager supports `_GTK_FRAME_EXTENTS`, the headerbar will be rounded, and the window will become a GTK (client side) shadow. The headerbar itself works perfectly fine without the rounding (as you can see in the screenshot above).

But you wanting to focus on the GTK4 port rather than GTK3 improvements makes sense. I'll just wait for that and get back to you if that has an issue when it is done!

**Comment by JerryCasiano** [comment]
> GTK4 still does not rely on a compositor

It does by default...

https://gitlab.gnome.org/GNOME/gtk/-/issues/4815

That's just one example.

But that wasn't the point anyway.  ;-)

**Comment by phisch** [comment]
Those even have issues on compositors that draw shadows, because they are not identifiable. (https://gitlab.gnome.org/GNOME/gtk/-/issues/3879)

Obviously it works on gnome, since their compositor doesn't add shadows to windows.

But the headerbar/CSD does not require a compositor for any of its functionality. You probably added this because some desktop environments would still draw their own decorations around the window, and the composited ones didn't, but I don't know of any window manager or desktop environment that would have issues with this today.

I thought this was a bug, because even if there is some magic that would disable the CSD, there is a setting for it in the panel, and that setting is not respected:
![image](https://user-images.githubusercontent.com/1282767/162435711-c44d0eb8-0370-4be8-96af-d9070db2ea76.png)

I'd suggest to drop the compositor check for GTK4 at least.

Anyway, thanks for your work on font manager, it's a great tool!

**Comment by JerryCasiano** [comment]
> I'd suggest to drop the compositor check for GTK4 at least.

For sure.

> I thought this was a bug, because even if there is some magic that would disable the CSD, there is a setting for it in the panel, and that setting is not respected:

That setting was meant to allow people to turn CSD off since so many were bothered by it at the time. But yeah it won't do anything in this case.

And you're right, now that you've refreshed my memory, that's exactly what would happen you would end up with two title bars on windows which I found disgusting at the time. :-D
